---
title: "Within-person network model"
author: "Marwin Carmo"
date: ""
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  message=FALSE, warning = FALSE, fig.width = 8, fig.height = 5)

library(BGGM)
library(dplyr)
library(ggplot2)
library(networktools)
library(kableExtra)
library(qgraph)
```


```{r data, include=FALSE}
raw_data <- haven::read_sav("../data/PCSNetworkModelAnalysis.sav") |> janitor::clean_names()

data_dictionary <- readxl::read_excel("../Data Dictionary.xlsx")

symptoms <- names(raw_data)[19:length(names(raw_data))]
symptoms_names <- data_dictionary[data_dictionary$`Variable Name` %in% symptoms,]$`Variable Label`
```

```{r}
# wide to long

long_data <- raw_data |> 
  tidyr::pivot_longer(
    cols = dplyr::all_of(symptoms),
    names_to = "symptom",
    values_to = "score"
  )

# person centering
c_data <- long_data |> 
  dplyr::with_groups(
    symptom,
    dplyr::mutate,
    z_score = as.vector(scale(score)) # scale the symptoms across all individuals and all time points
  ) |> 
  dplyr::with_groups(
    c(symptom, subject_id),
    dplyr::mutate,
    mean_score = mean(z_score, na.rm = TRUE) # mean person score in standardized units
  ) |> 
  dplyr::with_groups(
    symptom,
    dplyr::mutate,
    pc_score = z_score - mean_score # person centered score is the person deviation 
                                    # at each measurement from their own average 
  )

# revert back to wide

pc_data <- c_data[,c("subject_id", "pc_score", "symptom")] |> 
  tidyr::pivot_wider(id_cols = subject_id,
                     names_from = symptom,
                     values_from = pc_score) |>
  tidyr::unnest()

```


```{r eval=FALSE}
fit_var <- var_estimate(pc_data[pc_data$subject_id==92,-c(1,4)], progress = TRUE, iter = 2500)
sel <- BGGM::select(fit_var)
```
```{r}
st_var <- roll_your_own(fit_var,
                          FUN = bridgestrenght,
                          select = TRUE,
                          communities = 1:21,
                          progress = TRUE)
```


```{r}
qgraph(sel$beta_weighted_adj) 
       title="Temporal, Lag-1",  theme='colorblind', negDashed=FALSE,
        legend.cex=0.4, details=TRUE, diag = FALSE, legend=TRUE)
```

Concussion vs non-concussion


<!-- Do post concussion symptom net differ between history of concussion history or not -->

<!-- control for sex -->

## Within-person network model

```{r}
fit_within <- BGGM::estimate(pc_data[, -1], formula = ~ sex)
```

```{r}
summary(fit_within)$dat_results |> 
  dplyr::arrange(desc(abs(Post.mean))) |> 
  kbl() |> 
  kable_paper() |> 
  scroll_box(height = "300px")
```

## Network plot

```{r}
sel_within <- BGGM::select(fit_within)
plot(sel_within, edge_magnify = 5, node_size = 13)$plt

```

## Bridge strength

```{r}
bridgestrenght <- function(x, ...){
  bridge(x, ...)$`Bridge Strength`
}
```

```{r eval=FALSE}
strength_within <- roll_your_own(fit_within,
                          FUN = bridgestrenght,
                          select = TRUE,
                          communities = names(pc_data[, -1]),
                          progress = TRUE)

saveRDS(strength_within, "../out/strength_within.rds")
```

```{r}

strength_within <- readRDS("../out/strength_within.rds")
  
  
dimnames(strength_within$results) <- list(symptoms_names)

plot(strength_within) +
  theme_minimal()
```

